name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # SOLUTION 1: Add clean-up step for Windows metadata files
      - name: Remove Zone.Identifier files
        run: find "$GITHUB_WORKSPACE" -name "*Zone.Identifier" -delete

      - name: Setup Node
        uses: actions/setup-node@v3

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build project
        run: npm run build

      - name: Upload production-build
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist

      # SOLUTION 2: Modified upload with better exclusion
      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: |
            img/*
            !**/*:Zone.Identifier  # More specific exclusion pattern

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4  # Update to v4
        with:
          name: production-files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
